---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-webserver-secret
  namespace: lakehouse-platform
spec:
  encryptedData:
    webserver-secret-key: AgCzR2pR8uQofYNtu8DawWgRcxRQxyqq5yEy+V2IE+ZyJkq7jUO3Nw678HvpsQxlYjIA7/6dYy2u3+p17YMmDY4Mq1GU5A5t7TesDtw9WUMaibLZlY3oKf/vRIgzh5YuNdWledSOtYIjDIUklwDlTxLJywB59oHmyUmEoab828mqozwguHAYeIW22sNVkNYX2OC9v9Hyan2jdhbjYnNXlrUTnQFhqXuEQuiDvjrqgqfGNJy6qdYif2xUqBedDOLKDg8zPOcfGbyehsj3OL946boNhvEuEtlSyoHGrcGy+hgRRsu7deArFazyWdHHGAZlbRueKTPnvBi98uqXNm2YGr1ln2/yxtSdE/uF0zFozdMYJiw8+12/fO9npFAGc7pUe84jKWLdJO62SIt5rBeDqtqPG7UbiFkb4j4VSxop8sutYCUIrxzYsTEYsDh47Xl6YyciQoCh/41dgLteO8xKM/lLoiQPvHk3pacDLH5J5todYiiC4EXvNijy5tRU5s3afjDnpK+t3yZrMFlPIDImFgglN6YQQoMWWN2abAKGhN3JJBL9LJgUYt0B3xI+W/aed+fr4kB+nEsV4EP2+UfKHr74MvZrmOZuKK6ooBydB5iUvJVf9tfEYdt9WkHLs9apehdbvdjursglrO0XlzvVliwolnKD96BFbQ03v9d1GRx2zD1Lqqqo/jXJ7AahCrcYF7Vv7TBM4eK2ysA=
  template:
    metadata:
      name: airflow-webserver-secret
      namespace: lakehouse-platform
