---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-fernet-key
  namespace: lakehouse-platform
spec:
  encryptedData:
    fernet-key: AgCuXKdgrHmM0RAmYuA/FjPuVCYp3Tv0es/JBFIZBZKk9Nx2e33ab7auPCNLjU1cKplUrRL847YiHduwgyMYlJWV4AB+4n8TFutLXA6hAzDb5mwyXBDz5WvhgIV2DW57bpTWn4Qvzlc9YI7tAN41wezYuvHso4Ye/yPUYWN1qaE01qUqXqtNJBPgxK8XXe1B3vIq2xf7sFDfAkT3eS+VteJ5Z407UcZK4/MeLOfyu3dhzSVLO1mA3lAWo5w8fVrV9IsCC+knSiKZNEqpRfU+1r3sVpQ9rdTx8Xh4ZrsiWwElQg0m7yeS47LDl4hhj/n4n5yZrRlw7PtgP+6UdHYBHVN98t3tnGhvNZGGXmEKwNWqvAQ5xpR/J9zmTBvz7eJ48k21RvjkabJ2wMseUTUcyvLQ3d56Nud7urjJrS9xfJUOFCW1+rWaVP81LvFDOlVN/qvruurkAGrJ93sE1YShnsMEiGkAmphh/BVWEBU0QgeHTD9lJ2U0uDgGODnbeDD0N9QJYCTKX+nft82HPvacCuASphmp8UxzrNEeObm7XFDXaI6pN093bNH4ZDd0/2KKtGVR6dAOrQwSDyXYrrMjejUlWvTYJCgde2vH990NYA6QJG9L3M9zbevEFnDrW5RH2jj4sNAbpNNgQtADnRaEix+krWaFWAfRD7dwsyQnT/ooHTtHmEwYZWUfb1WQT5VlBLD6FINpc7/JrfTbtDN6wJ8PVElPxPay8QItwWEuWN5IWTKEGxQ17pnGpKhbDg==
  template:
    metadata:
      name: airflow-fernet-key
      namespace: lakehouse-platform
