---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-fernet-key
  namespace: lakehouse-platform
spec:
  encryptedData:
    fernet-key: AgCQFjDQ+gqlcyX4wzxIsTjCyJ3kTIMJq/Z2xYFy3EU8NRU0D/0UtHwnoNseVWvo843KW6yuD2/DbNpXv3oNquQ/kMQCVpEIkVy5hIXqyRL/Uz9UzjgNpgeIbgHPJntnyEFBSqItotyAsEWd9HpCw9RqQwEiNwNPigk4azGG7jTm5ddz5GBJEhZyNPdfIn7EL99bLmyVY/7YG0MaI640/0M8H0ZDriEZ2/upU+z1VKEI5w05lScacF19PVzhaUtk9v8F6yJ2P95Wh8f7KXR6nYjsVxXe+k7qqZaA1US2ZlEJ2QzolPLgX5dvh0l+FeDIc8440MEiTqvMe+pftzNn8mqIe7CUWNklU/vEazoHkPng0USHqF9iFeQsBynmjJ+cq0vFLjZ45UymLZ13G5ra5oLUFqwJW8BcslWWo2LofFRNmYpqtzihYTNJ4K50ydQt/umW7ZvAbbAXJPu3paJkXGkiCgcuAYQtrTzEQxDTIdiNAhDZOho51lbnwXnP1FPkm7IZ4htwXLDhH1B/JwVv1Fe4yj/3GLcaRah1qqQ6btonJh0Q3QzydF4UiVDKnVn9qSjIQ/WaaLEFzBtTe1HW/1HlNPIP/y94oEia/KSd5k0MQUPvudD8GGU1dXpKy3HmDhAnQOHnXgpeMIf7XsOkXCOnXJ5zMV9H2kbj92D0723EgNnjIgLrhKPVMtpM5uNet4GxbNqTxMZcH8KKmJg+hzgvq0cHXDlZKoqlS2CwmRd6KgqUS8Fbwl8b/88N6w==
  template:
    metadata:
      name: airflow-fernet-key
      namespace: lakehouse-platform
