---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-db-connection
  namespace: lakehouse-platform
spec:
  encryptedData:
    connection: AgCjK+946m8VzR3KgJqU6El2xgzASNkHWKZleIukenI0J/IXk0h9BdXkMOaQdfUMJ9CHVBiLkmpYUA4e6l1IVBkSZcDjssaarxrrlSzvEX3SQyP8B5j8aWBZnm5qtzvs765pmJ0oatHz/TjBDdICMg9/whhKXCApAHOxvuitRFu7Koz8C8ELUTDGKvR7y/NzdiYtcsoB7V/YIml3hxJg0CW07L9AmtcCPjyMRAnff8wYmwBGVY1bjlpbWdiZELAPY81FeJ3wEZM7H29hFL4MC1so+gycK2QO81YQpx0FPeHLaQgM2HrRSs1swj1rf4JXxg44N0lgumLQH00Abqy8tr1caPJ/3iCpL06nMGGfv8dBjQHuUOLU2kQwe5d04UeXXavT84oT9dhzJqidOr6V3FLzxIfaF6nJUan7vx1yPmmXrfmBnwpfOrdbnSL/F+ShG0ZI+7crhgmCRTFmIBvTINkiRg2x6ETD+hJflDYVAdX10l2T43DsgLnq8XI1Xx2AxVK0wGUCr5nRE/Z4ZzjBmSsnO9RAFk7S3xW6R/6tLU4FMsp1Nn8/4UuYlif1S1cTEK06E8DpdgcrPakNFCsm9iWtF1VqxYNaXpr6X9Yvhe/r9U2UnXBrvuClA1YXwCe7fhxcIJLUw9ZrEL+fWfl1RmB1nYuO05M+XJGZWi8pYIRhghxg41/yyqP+JTSSCV0iSCEkl09c+1n5NlMP0N8XgJQ1zDHvVxvaVopgfG6CaL7PL8ALE4iR32dpsnzIoYL7pLgPiADqBNx8U2W1lsz3QgVanpq2dltw4qGFWn+IqnTA7Ni3wg==
  template:
    metadata:
      name: airflow-db-connection
      namespace: lakehouse-platform
