---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-fernet-key
  namespace: lakehouse-platform
spec:
  encryptedData:
    fernet-key: AgCVSAXSB/C9BsZTzr17VD6bgCfHZi9mvThsaNrfwEDVVMfNwKE+mz5EAitEI2VfVwWT4V1SWdjSwi8BKBfOw1WphK+1OnL2Ro7YJ402qsJ78E0kbsvLmW2hUrkNl+1Ec3v1NiJ0w4RfE5YDcir56mwruEv5TO9D9VQUlSwTdjJcMhhj2J+gZA/31RC4J5CKdNW/AtynZdUPgo8gWJJzodTPF6M6D0lnhJw3xJI0u9NtP+ye+MFIYHwl0FiJzWNuzO2L7IraSjH8sHjcLKwFbTzxKTvFwGI4bqToTDBUyK1VUao2VV+c4Ckjdftz7tz3iF/eRY40ltu3t4q/91z3N+u4OJhNzn8hlgyAWSKq+stXRC8QhfK1en0Wyc9sggvVkq6Mwm2Obi4XG2mUbu5jhCvNhcPuPlJqg/REKDJjHDtqFkmvo3Mfv9rx2CHNO/ZMFLAFPijpgcHBPIuXiUKNbBGaYwyopAy9qZ8kf/+M2GBklMGXY5OiCoBb9XWovdtmUj50zGmcqVA3PfQZuCPhahBRCAypxmCLtJgxmBR3nrY3lzdKFazh9872GkW71tXERdlRumtn6+K+djS2/wJ6diBcc9TI25visiXYjTfIj6aExwiL2X/0ar1p9ttUIk5zOXN+h9o0Xo4miek9njynbewkJnIV3X9KQGP7AGMPZM/1qXutqOnvLMvuj9r7QxwdXucke3O4D8+Um2LcXZwXQupNvt4ZIudBKlxFb9vf88cKghYK25c2EMdlHUC03g==
  template:
    metadata:
      name: airflow-fernet-key
      namespace: lakehouse-platform
