---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-db-connection
  namespace: lakehouse-platform
spec:
  encryptedData:
    connection: AgCwqvPCZ2LskLYk7Zjkg9fRG4AjV4hJSobmvbH8jK4a7FL9pFs7d63cHLOFEfqz0hlDsASLhv94QsTdFjO31Z3gCtV83GchLgNnKn6pthjK34V5Gneehsc/wsFvGIrj7h0OqBEKIMay42ugvC72Pn97+UNg9v/JZdtCc6LvGPA59hdvPF7aeqa+E8wOJAQGgIW5vtf/Vq21j36zuzpDJ7OQkapW5WKSbHGJ2qi8kkgVj7zba6CQRPkqsvF3sLilnrLDMtfS9m2TGI5AhM4ExwkROewUjP0eM27WjUXV+y6duwKb+n/oXpta8kOgF1xaetNrwHxOrGu2COiPlkt9jxjZ3P0AYiSx3iCD/kyk1Yl1Im0QAYV5e2GD3WRCjSDmhFRSL6DE5Jx2JcGKROlzM4RVoVxuTAOdlLQPio0upAYr3R7UIt5bpc/KW3Wz0ADK63dtJfUxadAcMCwTaM+o+qdhWTqlAiJmNiZLQrr/th9nquMOrpgTZ/DP/JdL4tpwFOggQUaBXMZrELoEXZOZNT5DcMnENTy193FHn6RsM+Ulvzv0nZG8vxumfAFqqaOeuWiFZMCBZ8yHfcvg8owKsifNt5SjO4IO4/bOgfsnPs50tRTUsjsFUSFktMSc043dea0cKx8SJyE1JyOUjsA96XHK+elfeycEt2CI7JgK/gMB4lUKm605NVsH6yjaNH9bC7sVng6V5PvpxMoC/qk75BmDGmqScxPk9w4mnp4DR9Hmt4ckH3+UL9Jr+UOJAFyeyfPYEnrGSGMCz6yd+zVODipttwitVYpvQFOJum7lNPA0ycXRmg==
  template:
    metadata:
      name: airflow-db-connection
      namespace: lakehouse-platform
