---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-fernet-key
  namespace: lakehouse-platform
spec:
  encryptedData:
    fernet-key: AgAabswhi5toecMD4unbvQAV1uhn4tioIIU7eWc0IdB8wIKCeESQDpIfk3bWzCRGRY4ZN/Dg4P5kfkBsyTNjJ5AladDfN3uWhLXfPG7FyoGrOca+uDvT89BD+eBAqAh+gs2PZHcPH2OeP2KQVoNCT3ltRfRvQQSW7QUxkn3Oz1EoGg0m0Jy4UZN6cD7B5MQXuk3TGHi2LqAZJzbicWqdquGqD+5wQd9uRWBFemm841xcvV1EGzTXQbg5OjWpPFURVcBWwng+SdOm7EDtMNMQr4QiVjid5I4ZqyCN2eNLHTptYiQSF20wl2V1fhBeG4r2H8muW+BcGWgUcOtmMMzIdwhggQEGdXxrzzSXm7SuFoQEI70uhFWoLRk50Jats8JuJ0QMGeHUSXyn6Bwbtf+rwGLo0pQttYhVyTNXFFdQUu5AtTVm7YBjXGAxVP5RCFWyC9JfP/WRy/ruB4bKSpaDotVeEXKusWKrX14FAsd5s1e2HKa7fYEMN4VXsVBnz4CDYldtD6ZOBABxg9H3Qoa3htOXgmHsjWGAiQw013zAVUMYfj7Q9sv8yhG8/4h+8BF25hgZEOtrNH9a5etnvkeZhxBiX2pMs50nl5duYnBZVgiyjQieuzeMb3wCTiMEBJ2LmLu/hEsS2BY/Chul1q6Lvlzgm8kVedsm2jnionABBXf/j644NRKI95wt+wtCKn34UAt5p54BPFGhnfgsFgn3ZKNaHNdaOAUNQ4cgTpF6KoTwpQm3U+KV5lQoJcF2qQ==
  template:
    metadata:
      name: airflow-fernet-key
      namespace: lakehouse-platform
