---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-fernet-key
  namespace: lakehouse-platform
spec:
  encryptedData:
    fernet-key: AgAZhh2wo7DzUByB7AGPQVHo4oUV29kGOa1Nz66RecQp5U9x8gBdgGnUJcaCfgb+h9MZMKc35X73XDu2hoinwAX/k339zJKlMmSVTKK/Latcdx8yVnEhovW+cAyWPuLgSP0D7nS7BE9AJdkWq2ftgc1EWhYIntXumff3EME8FgtOOw2T62lMRafUqL+k+PSkS/mXRJKZP63utNdn1olUGnEzIdtI6AWfotRJZDaifvDGpy8xKb31o92bg7FMKfpy9076LJKPsz6iqWt/ym3+kS+LpNjjOeCmO0SEljQPIDn1Ndbk1g5WcWREd2/0H/ixh4ghyKYcEPeX4H0QjBcT5VQVWuC0OR2rBEbcoCko2hTs08xTvSShhwkyP4RqSd9bsGTQXlttXmVM+7kJKiq/+rAclJCS66judXRYWU2tcOFvAWaqjx+42rft5676Cegm2Oarp2Y4JQ75VpUMOF5NvfLNqUGRqMojrhN8fFGwwy1K9Q4WQ6/xYUGH2vKD+etFt70Lx8SHA37NDS4bXo7TVinPcHyTHseE6cTx74D/VUzYBUgnOKCb3ACeuD4Nm044do0jgeIUI982hWn4ohAAQGfScP7lpGeI9+qa2IAXtn2Q/ntCmVohg9djMEzFhhaCYo+yoDLRbyCQeAfVmrNBP1pJNkyqHwp4QXCn7y1C6MmE+oFRjod03zvWDg4rDHkzP6PBGR+3vD5Pm/LueTOYdbObgkR7UJTZHOKv8DsjpSy5ymBQJt+2MoLuR7LJng==
  template:
    metadata:
      name: airflow-fernet-key
      namespace: lakehouse-platform
