---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password
  namespace: lakehouse-platform
spec:
  encryptedData:
    admin-password: AgCFf/UIMX2++yp9kMKIVgfVXzDzcVjZq6vtcanZt0gcGfqugzQcQyJ3Fww5QkqOFy/1MFrKL5GSLvZKyYNsULYko+mMgaY/1UcPVKc0Fn8oqQM8qeXaaH1UI372GLA3iEdvUFq9s6Hg9qVotoLr2JTkBhzEBeq5oZaMaB6f/2qJeNK2EoDEbL8kraYbNo9U6KnTDxaKMYJ8/ObUy6zqnzLKH9ojMGsl7+c8W/jObN4xMYg+Hd+N5vXfAUMT5ftJwThJbhIthy3tsrn2cbzJn2dt9N68I29EjPEejLBiC9Z20HDIUJ/uleS0RVhOGpjdGhJdtISKXvl4zpby4qkavt4WAJ1gf/wic9yGmSogVvVhmOf8BIeH5sJklxt4BEITzFowyf+nidBV76D9Kg+x4ClOUko0JUOiswukaYFvLRUciP/sR1eItRdrXxSCGgs9s6VlUCtg4POq5FAMbUDLELOrjZhOrW5QeoTvOnHbbhsCLLsBFepox+KftjFCuocTh17O0caY19cHN4im8Uuf0QJuTyam5m+nP7DtTdRlUDiOmVIYQgWeYf0djoaeTblsy/VOqTzpPiFe1cykCSbeW4uJuDnptaNsMXeevqXHJDsc9jrc/Av1jTGVz4snCdQjhHfdoivKluBk6/jOr90Fy0XX1+Zwm1WCnMZaMEpxO+HHyqZhEDsxFpHeE1/Y6uXtSXnjrt7sCSHoYwE=
    admin-user: AgCdlgKtu9EMI1vpv4sx4mmD2VcYdKIrsp2AaH1cufaK4mdCBJ8r19GZAE6SVUNaQzb6vEhPpFNwvjo1TSQcEyZutn2VZl1lQfl5BjkbiJ+78DRAuYkWuCo/GvSlOuJaIOopKXB6EmhPNIRn43BdV43Mi9h8Dc9Nk2id8pXVuxXHwmnZVeywRbIKb27DU/dCdnWchHHfT0Nmmyc4GhxL2lfjbOfrXI9cOHrxrizoa+XOEqTluo35LZvL9FN9jIv2QjN50bhaHW3cSnM4WJP+xTN9kKvKSaUciYffniLJMa2vPNbukhKjNuz4iTA2Ebma0alSYOPnFeXvrjOJOnhUYPbFfyPUhV+94S/ZKEXqk80BF1IrexL/3DwiiHQekN8TYJHCnX7PkOmHclbjF7iTZ096LSCVTv0UxTHb5B3kaZz/3n6/PcPmTPCkcu7PdRia02Y372I9362RItDq5LPSupQnULc7Yt7grSG1XSeX6PBY4+/LdbbbY2MUWa9nrf8gGwOGsD4oahNueA/Agnyrltg6WKuc/B5sEAH7+0i1O4nwkFq3F9/E3zxLO4gahNn95iX0jUAj8W56cy8B5hyJIyhVDo0YZkVFYkmcEnpbToG3SuCatWXbT91GvTF90bl4zpPIPVyk+DREYKb4m3AnbDOdF6BXIhUH0MU6lHpiFghpJBoDDtmti8mdlglQA+SwWoqptWOPJnp3+ik=
  template:
    metadata:
      name: grafana-admin-password
      namespace: lakehouse-platform
