---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password
  namespace: lakehouse-platform
spec:
  encryptedData:
    admin-password: AgB8f4ZlxUZJnvrS2Jp2uZemTKXFrgPElnZC3nsSwyYkT6WWOI33WmcYVQR01+XQuKw2DHYI3UQt/1tebSDNq00t+aCWlWajfxHXSIE6j9elVxi8kG+//RzS7ey3df8cuV7+zKvztdL8uhwG+2Xx+Hxjp+fFG0Od9cL9UoIkHdO92Pzqyr7xkBuxyHE3Gzq0XAqd7+OeGBZOewuLyd1Uy6HEggZ/f6HsbkMwkRnmNiUWvTC73U9WKKiq2Mbabgk4lZ/21cY3HOUzsHR7NG0JOq/AaYJgteX6ZxojZf3Pn5Uy2DoNqVCW96Z8SiptpGmDZRjcMkEhN8bp8zm5bcVYM6GiH/RCu44lGuVGjSEpX/jlLGa1iu/vKqh2Qik+wk/Eaw4O++sPaR44TzawZwzw7rsoCEcahtUC7EfSXxbizQmupsQ5R0p0YmpkArDqmeLx+rqP2m9Dp9thGEx8SW0ynKXBtp4tPBHBxub+WeUUayVCWKxra+ODB7AxJ9lkkjrfW20AG4kuHbGxXVo2W5IPMnUoamdlHFHxSxvVLVkMhFEEX0pr7NmX4utTyQYW9gNjHgtYEMOSiGhF6CoSI9ZdzOvQ+TWZbGGLteyhybPMQuEz6Kn8DsLRSBfh0GOvChP62iYfTUPxN91nnusgSfw+u3SmPPYEirUTHzaHImxfUX5/40kgti0UsprjklTK0rNgLMSW53k9agMm
  template:
    metadata:
      name: grafana-admin-password
      namespace: lakehouse-platform
