---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password
  namespace: lakehouse-platform
spec:
  encryptedData:
    admin-password: AgAy2w2jHlvnF4UGQ95z8C1aJe6x6bEM5YYuri45L9M6nvr/cscGXGrrVq3J5xi1mKgElqO2Yzt7D/3JjnPcoj3zAM9GEtCk6lICmR2aJBOiZ4/GnYxuwiM2qCFVBUrswLZxNy0gZfbLGHSg8Gu3ynxfCq6W4cxBo2GrtGe6nRNtud5vYVxpWQlgMiv6Kp/RJ/ni0iOBGUrxZSOGRyjCTcIPROX4zRr8uRJSU6OtR4S00bYN2TQksnh4QYZn5S9/O9ws3iBqwZaVg9uxNQfFAlk4IjnclTNQmrp0XnRRKuk3A+Coj3eyGVvpSNpcIVcSAsSRIadJ6/BKbFg6YfUOjF5uRCdaX5lpwP0HIsC/bEESFxtpDOxzq16msPV8u6a0ZMGOoGc+OK3ImZn0oi6oXNSbkMqpWCOyjG5yJKR5XDrGJI3HRqBVkv47+sHfiBLKdPc90GPbTtg/1ETfNpawrh8r+CwoqL2PHdVA4xN3H6LXJN8aZGDJTWap87q17xO76d+JtuJZ4aLfa75ZWZLpzkRIC62GbIRnU9sH2WgDmbzE7O47M1NGmB9KPO49MjuALSl3fBi/wxjz2rDuSuhXfiubxF1vgJdDvufCwWMdbtBxo7+tGo23jtH4O9He/+0VyDa8Qw8+iKdLDA5SRPCbrlkRNrRRtgSajv3N/YXI3AhCdC4w7/d8VhmunbGjoMsrVOiPngfLD06c0HI=
    admin-user: AgB3ORLud+dGry6vsL5KB/myMhuFiKoQGHZ7PlYyi5D09LbbVC83bC9tgSLaYuQ7dcLUOU5sb2Rq1wRl49plRjJl2U3TCRtAr9kbwW3DTyBfFuGdivQDI4c+Zs4FTr5LBCwQEmlQcFDesnt7NMKKtRy9lrJzrxJlKSQJgcPNLEUL66zBKvCYY/tFCx03yPhfNmgtwmYB+YYQZ77+T0Nv4/Om1+t31Y+oMl15CFY3a3+2V5t1riZ5IbEmRKWa/cGHJZe/eeUcsyLijK/Mr9sLD7gzi8xHNtX8YkY00PR/Sc0AVt3qR7zNh7g2ewX2wgHN9rvcxWB6pTIcFzOb3oNZQu0tSSW0lMvu35Vxlu6IXPmSj00tsw4Cc85CXUUY3AwnY46rcC8zXKIVZKBgDiXt+WY4S7UByxge7sEGcMSL2KWP30v9oMKFQHtCjm3rlvqjDszmlL9Zz4/HAOU9xokxzecfOipwzuHmAe9VyVNsMnBvMpuEWSx2Ku/+KNF26wOlASQXpBgd+Qj8pfrZvuQrzONRm5dAuwzwr2XTt6vyObjISx8d5PJNvFkxosVNsF0wjH6CFzbHEP1Fh6wtx2YGWmUrsFLQsN6SxYzoPZvBEBF+r7PsKEOA2b3HSQmDcWMZxA3D3RJ2JTw8BV3FIjioD69Q53Bj39Qwb4nKs0puie0WXIHZDRzMztk/tSoA1keWBcjOtQoQe8HS5GM=
  template:
    metadata:
      name: grafana-admin-password
      namespace: lakehouse-platform
