---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgBwwcUZJsHs8FQ1/lXD/W9eMTwivxfB8QHERUwsuhHy1PrOpVjgTOGqGU2A+fyAeFtcglt7o08JflaIPPiqouftby1QQzvp9vTuW4+5hnYEUIxdeXnLS7zepI2geZN8CFNnHUmS+ousDSTdlDm0yRxzs8b+e2zYljGdJqdLEHtuv4IpONwWgo0pdDRXxs3HaDbokeRJ/1EPEe8286089wMj6DesmjDLjHSJdtvlvKTJLaCZPisxc15yk3OifEYoVJmasZi7bBBsZ8d5Hcg/nA5dwUTTEPDUKNqiZ/ZdCZgB9hnhEAznbyXHC+nH+jn3Y8pPpiCn0Zy6uV3IZEZ4PvHxSUxW5oGieag5TLO1nF3kOpODoZZIdl9W2yHvTJLL+3sp8U38gFkaBGoneglxxO4541mgKfzkgecmDYzi/YlaJVPwczF6BkK7KClcPkZ82PFWwqjLPFt1w1KFE3nKOkd7GmNfq7pAL/cS0zsWmRSwqQZ5mehtr4VCDGKGiotYtBHoyXWJiHlt4YcvFo2WskCrZZBS+kqohnbYDjLfBg344HjJvcYg7WR71BUvPrWBW2I+SOOlbBn0bjpPhxF69dCNVsb1ruY0HYA+VJow70qYfqq/YA8QMlc3NWSl7zXNnx3F00dRhOfIKMvHVQVOSk4sjdMRbaLexNAKyGGWm024p+Zn4t5hhbL3/beVf8CnJM98cJrCWcw6
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
