{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iceberg-catalog.fullname" . }}-metrics
  labels:
    {{- include "iceberg-catalog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "iceberg-catalog.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: {{ include "iceberg-catalog.fullname" . }}
  labels:
    {{- include "iceberg-catalog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "iceberg-catalog.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
{{- end }}
