apiVersion: v2
name: airflow
description: Workflow orchestration platform for Lakehouse
type: application
version: 0.1.0
appVersion: "2.8.0"

# Dependencies - reference upstream Airflow Helm chart
dependencies:
  - name: airflow
    version: "1.12.0"
    repository: https://airflow.apache.org
